#!/usr/bin/env bash

# MySQL Connection Details
MYSQL_ROOT_USER="root"
MYSQL_ROOT_PASSWORD="$1"
NEW_USER="holberton_user"
NEW_USER_PASSWORD="projectcorrection280hbtn"
NEW_USER_HOST="localhost"

# MySQL Commands
MYSQL_COMMAND="mysql -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e"

# Create new user
$MYSQL_COMMAND "CREATE USER IF NOT EXISTS '$NEW_USER'@'$NEW_USER_HOST' IDENTIFIED BY '$NEW_USER_PASSWORD';"

# Grant SHOW DATABASES, PROCESS, REPLICATION CLIENT privileges to the new user
$MYSQL_COMMAND "GRANT REPLICATION SLAVE ON *.* TO '$NEW_USER'@'$NEW_USER_HOST';"

# Reload privileges
$MYSQL_COMMAND "FLUSH PRIVILEGES;"
