#!/usr/bin/env bash

# MySQL Connection Details
MYSQL_ROOT_USER="root"
MYSQL_ROOT_PASSWORD="$1"
NEW_USER="replica_user"
NEW_USER_PASSWORD="replica"
NEW_USER_HOST="%"

# MySQL Commands
MYSQL_COMMAND="mysql -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD -e"

# Create new user
$MYSQL_COMMAND "CREATE USER IF NOT EXISTS '$NEW_USER'@'$NEW_USER_HOST' IDENTIFIED BY '$NEW_USER_PASSWORD';"

# sudo mysqlGrant SHOW DATABASES, PROCESS, REPLICATION CLIENT privileges to the new user
$MYSQL_COMMAND "GRANT REPLICATION SLAVE ON *.* TO '$NEW_USER'@'$NEW_USER_HOST';"

$MYSQL_COMMAND "GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';"

# Reload privileges
$MYSQL_COMMAND "FLUSH PRIVILEGES;"
