#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinetely and killed conditionally
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!' && sudo rm -f '/var/run/myscript.pid' && pkill -9 -o -f '100-process_and_pid_file'" SIGINT
sudo touch /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
done
