#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinetely and killed conditionally
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command' && sudo rm -f '/var/run/myscript.pid' && exit 1" SIGQUIT SIGTERM
trap "sudo rm -f '/var/run/myscript.pid' && exit 1" SIGQUIT
sudo touch /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
done
