#!/usr/bin/env bash
#read and cut specific portions of file
file_path="/etc/passwd"
while IFS= read -r line
do
    printf "%s" "$line" | cut -d ":" -f1,3 | tr '\n' ':'
    printf "%s" "$line" | rev | cut -d ":" -f2 | rev
done <"$file_path"
