#!/usr/bin/env bash
#read and cut specific portions of file
file_path="/etc/passwd"
while IFS= read -r line
do
    if [ $? -ne 0 ]; then
        break
    else
        echo "$line" | cut -d ":" -f1,3 | tr '\n' ':'
        echo "$line" | rev | cut -d ":" -f2 | rev
    fi
done <"$file_path"
