#!/usr/bin/env bash
# This code willdisplay something with a condition
counter=1
while [ $counter -le 10 ]
do
    if [ $counter != 9 ]; then
        echo "Best School"
    else
        echo "Hi"
    fi
    ((counter++))
done
