#!/usr/bin/env bash
# This code willdisplay something with a condition
counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter == 9 ]; then
        echo "Hi"
    fi
    ((counter++))
done
