#!/usr/bin/env bash
#displays bad luck for 4th iteration, good luck at the 8th, and Best School otherwise
counter=1
while [ $counter -le 10 ]
do
    if [ $counter == 4 ]; then
        echo "bad luck"
    elif [ $counter == 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
