#!/usr/bin/env bash
#displays 1 to 20, with a message when it is a supertitious number from a country
counter=1
while [ $counter -le 20 ]
do
    echo "$counter"
    case "$counter" in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    ((counter++))
done
