#!/usr/bin/env bash
#  Configures an Ubuntu server to resolve localhost and facebook to different IP
echo "127.0.0.2     localhost" > ~/hosts_new
echo "8.8.8.8     facebook.com" >> ~/hosts_new
cat /etc/hosts | tail -n +2 >> ~/hosts_new
cp -f ~/hosts_new /etc/hosts
