#!/usr/bin/env bash

PID_LOCATION=/var/run/

# Check if there is any process
if [ -f "$PID_LOCATION" ]; then
    # Fetch the PID from the PID file
    PID=$(cat "$PID_LOCATION")

    echo "Reloading Gunicorn Gracefully..."
    kill -HUP "$PID"
    echo "Gunicorn reloaded successfully."
else
    echo "Gunicorn is not currently running."
fi
